import fitz #importing PyMuPDF
from config import google_client, collection


# get_chunks() takes a fitz.Document object and splits its full text into
# smaller pieces called chunks. Each chunk holds at most 500 words.
# This is necessary because AI embedding models have token limits and
# searching smaller pieces is far more accurate than searching full documents.
def get_chunks(doc : fitz.Document):

    # Iterate over every page in the document and collect all text into one string.
    data = ""
    for i in range(doc.page_count):
        page = doc[i]
        text_data = page.get_text()
        data += text_data
    
    # Split the full text string into individual words.
    words = data.split()

    # Group words into chunks of 500, converting each group back into a string.
    # " ".join() reassembles the word list into a readable sentence format.
    chunks = []
    for i in range(0, len(words), 500):
        chunks.append(" ".join(words[i:i+500])) #converting every 500 words to chunk(string) and storing in chunks list
        
    return chunks


# ingest() is the main entry point for processing a PDF file.
# It opens the PDF, extracts chunks, generates an embedding for each chunk
# using the Gemini Embedding model, and stores everything in ChromaDB.
# upsert() is used instead of add() so that re-ingesting the same file
# updates existing records instead of throwing a duplicate ID error.
def ingest(pdf_path):

    # Open the PDF from the given file path and extract text chunks from it.
    doc = fitz.open(pdf_path)
    chunks = get_chunks(doc)

    # Process each chunk one by one — embed it and store it in ChromaDB.
    for i, chunk in enumerate(chunks):

        # Send the chunk text to Gemini Embedding model.
        # The model converts the text into a list of floating point numbers
        # that represent the semantic meaning of the chunk.
        # embeddings[0].values extracts the actual number list from the response object.
        result = google_client.models.embed_content(
            model="gemini-embedding-2",
            contents=chunk
        )

        # Store the chunk in ChromaDB with three pieces of data:
        # - ids: a unique string identifier for this chunk (chunk index as string)
        # - embeddings: the semantic number list generated by Gemini
        # - documents: the original chunk text, stored for retrieval later
        # - metadatas: extra info attached to each chunk — filename for filtering,
        #              chunk index for ordering
        # upsert() updates the record if the id already exists, preventing errors
        # when the same PDF is ingested more than once.
        collection.upsert(
            ids=str(i),
            embeddings=result.embeddings[0].values,
            documents=chunk,
            metadatas=[{
                'filename': pdf_path,
                'chunk': i,
            }]
        )

        print(f"Chunk {i+1}/{len(chunks)} done")